### ISSUE TITLE
Undefined is not a function

### ISSUE THREAD

**Issue by ianjamieson** [spatools/grunt-html-build#57]
Here is the issue I am getting:

```
$ grunt htmlbuild  --verbose
Initializing
Command-line options: --verbose

Reading "Gruntfile.js" Gruntfile...OK

Registering Gruntfile tasks.
Initializing config...OK
Loading "Gruntfile.js" tasks...OK
+ build, default

Running tasks: htmlbuild

Loading "grunt-html-build" plugin

Registering "/home/path/node_modules/grunt-html-build/tasks" tasks.
Loading "build-html.js" tasks...OK
+ htmlbuild

Running "htmlbuild" task

Running "htmlbuild:dist" (htmlbuild) task
Verifying property htmlbuild.dist exists in config...OK
Files: path/to/css/css.html -> path/to/css/css.html
Options: beautify=false, logOptionals=false, relative, scripts={}, styles={"critical":"path/to/css/critical.css"}, sections={}, data={}, parseTag="build"
Reading path/to/css/css.html...OK
Reading path/to/css/critical.css...OK
Warning: undefined is not a function Use --force to continue.

Aborted due to warnings.
```

My Grunt config (I am using load-grunt-config so this is stored in a separate file):

```
module.exports = function(grunt, options) {
    return {
        dist: {
        	src: 'path/to/css/css.html',
        	dest: 'path/to/css/css.html',
        	options: {
	            styles: {
	                critical: 'path/to/css/critical.css'
	            }
	        }
        }
    };
};
```

More detailed error:

```
TypeError: undefined is not a function
    at Object.validators.validate (/home/node_modules/grunt-html-build/tasks/build-html.js:196:44)
    at /home/node_modules/grunt-html-build/tasks/build-html.js:245:39
    at Array.forEach (native)
    at transformContent (/home/node_modules/grunt-html-build/tasks/build-html.js:242:14)
    at /home/node_modules/grunt-html-build/tasks/build-html.js:306:27
    at Array.forEach (native)
    at /home/node_modules/grunt-html-build/tasks/build-html.js:295:22
    at Array.forEach (native)
    at Object.<anonymous> (/home/node_modules/grunt-html-build/tasks/build-html.js:291:20)
    at Object.<anonymous> (/home/node_modules/grunt/lib/grunt/task.js:264:15)
```

**Comment by ianjamieson** [comment]
In tasks/build-html.js on line 195, could we add the following?

``` 
if(typeof validators[tag.type] === 'function') { 
                    return validators[tag.type](tag, params);
                } else {
                    return false;
                }
```

**Comment by SomaticIT** [comment]
Do you have something like that in your Template file ?
```html
<!-- build:anything -->
<!-- /build -->
```
Do you use another grunt plugin which use this kind of tags ?

**Comment by ianjamieson** [comment]
That was exactly the issue. I was using grunt-usemin build tags as well which were being picked up by grunt-html-clean and then not understood.

I just separated the logic out into two different files.

However it would be nice to print a command line error rather than to have a JS error which breaks the whole build.

**Comment by SomaticIT** [comment]
Ok, so you could use the `parseTag` [option](https://github.com/spatools/grunt-html-build/wiki/Task-Options#optionsparsetag). e.g.:

Gruntfile.js
```javascript
htmlbuild: {
    options: {
        parseTag: "htmlbuild"
    }
}
```
Template.html
```html
<!-- htmlbuild:scripts app -->
<!-- /htmlbuild -->
```
I will add a custom error message to notify users and add a `allowUnknownTags` option in the next version.

Thanks.

**Comment by ianjamieson** [comment]
Ah brilliant, thank you!
