### ISSUE TITLE
Using with load-grunt-config results in pkg not defined error

### ISSUE THREAD

**Issue by Per4merKC** [spatools/grunt-html-build#90]
First of all I'm pretty new to Grunt.  I was able to get grunt-html-build working *perfectly* if I follow the instructions in the docs; however, once I break out the configuration into grunt/htmlbuild.js using _"load-grunt-config"_, I get the following error:
```javascript
Warning: An error occurred while processing a template (pkg is not defined). Use --force to continue.
```
Interestingly... if I use the --force option, the html files are generated perfectly so I'm not quite sure what it's doing.
### Here is my gruntfile.js:
```javascript 
module.exports = function (grunt) {
	require('time-grunt')(grunt);
	require('load-grunt-config')(grunt, {
		init: true,
		pkg: grunt.file.readJSON("./package.json"),
		loadGruntTasks: {
			pattern: 'grunt-*',
			config: require('./package.json'),
			scope: 'devDependencies'
		},
		jitGrunt: {
			staticMappings: {
				htmlbuild: 'grunt-html-build'
			}
		}
	});
}
```
### Here is the htmlbuild.js file:
```javascript
module.exports = function (grunt, options) {
     return {
          dist: {
               src: 'src/index.htm',
               dest: 'dist/',
               options: {
                    beautify: true,
                    relative: true,
                    basePath: false,
                    sections: {
                         layout: {
                              header: 'src/layout/header.html',
                              footer: 'src/layout/footer.html'
                         }
                    }
               }
          }
     }
};
```
### Here is my *simple* htm file:
```html
<!DOCTYPE html>
<html lang="en" class="no-js">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>Document</title>
    <link rel="stylesheet" href="/styles/global.css">
</head>

<body>
    <!-- build:section layout.header -->
    <!-- /build -->
    <h1>Welcome!</h1>
</body>

</html>
```
### And finally... here is my --stack trace with -d -v: 
```javascript
C:\ProgramData\scripts\NewVETR>grunt htmlbuild --stack -v -d
Initializing
Command-line options: --stack, --verbose, --debug=1

Reading "gruntfile.js" Gruntfile...OK

Registering Gruntfile tasks.
Reading ./package.json...OK
Parsing ./package.json...OK
Initializing config...OK
Loading "gruntfile.js" tasks...OK
+ default, dev, prod

Running tasks: htmlbuild

Loading "grunt-html-build" plugin

Registering "C:\ProgramData\scripts\NewVETR\node_modules\grunt-html-build\tasks" tasks.
Loading "build-html.js" tasks...OK
+ htmlbuild

Running "htmlbuild" task
[D] Task source: C:\ProgramData\scripts\NewVETR\node_modules\grunt-html-build\tasks\build-html.js

Running "htmlbuild:dist" (htmlbuild) task
[D] Task source: C:\ProgramData\scripts\NewVETR\node_modules\grunt-html-build\tasks\build-html.js
Verifying property htmlbuild.dist exists in config...OK
Files: src/index.htm -> dist/
Options: beautify, logOptionals=false, relative, basePath=false, keepTags=false, scripts={}, styles={}, sections={"layout
":{"header":"src/layout/header.html","footer":"src/layout/footer.html"}}, data={"version":"0.1.0","title":"test"}, parseT
ag="build", processFiles=false, processPath=undefined
Reading src/index.htm...OK
Warning: An error occurred while processing a template (pkg is not defined). Use --force to continue.
  at eval (lodash.templateSources[0]:9:11)
  at Object.template.process (C:\ProgramData\scripts\NewVETR\node_modules\grunt\lib\grunt\template.js:66:50)
  at C:\ProgramData\scripts\NewVETR\node_modules\grunt\lib\grunt\config.js:66:27
  at recurse (C:\ProgramData\scripts\NewVETR\node_modules\grunt-legacy-util\index.js:127:14)
  at recurse (C:\ProgramData\scripts\NewVETR\node_modules\grunt-legacy-util\index.js:119:20)
  at recurse (C:\ProgramData\scripts\NewVETR\node_modules\grunt-legacy-util\index.js:119:20)
  at recurse (C:\ProgramData\scripts\NewVETR\node_modules\grunt-legacy-util\index.js:119:20)
  at recurse (C:\ProgramData\scripts\NewVETR\node_modules\grunt-legacy-util\index.js:119:20)
  at Object.util.recurse (C:\ProgramData\scripts\NewVETR\node_modules\grunt-legacy-util\index.js:130:10)
  at Function.config.process (C:\ProgramData\scripts\NewVETR\node_modules\grunt\lib\grunt\config.js:52:21)
  at Function.config.get (C:\ProgramData\scripts\NewVETR\node_modules\grunt\lib\grunt\config.js:46:17)
  at Object.module.exports [as config] (C:\ProgramData\scripts\NewVETR\node_modules\grunt\lib\grunt\config.js:12:19)
  at transformContent (C:\ProgramData\scripts\NewVETR\node_modules\grunt-html-build\tasks\build-html.js:333:28)
  at C:\ProgramData\scripts\NewVETR\node_modules\grunt-html-build\tasks\build-html.js:432:27
  at Array.forEach (native)
  at C:\ProgramData\scripts\NewVETR\node_modules\grunt-html-build\tasks\build-html.js:407:22
  at Array.forEach (native)
  at Object.<anonymous> (C:\ProgramData\scripts\NewVETR\node_modules\grunt-html-build\tasks\build-html.js:403:20)
  at Object.<anonymous> (C:\ProgramData\scripts\NewVETR\node_modules\grunt\lib\grunt\task.js:255:15)
  at Object.thisTask.fn (C:\ProgramData\scripts\NewVETR\node_modules\grunt\lib\grunt\task.js:73:16)
  at Object.fn (C:\ProgramData\scripts\NewVETR\node_modules\jit-grunt\lib\jit-grunt.js:126:30)
  at Object.<anonymous> (C:\ProgramData\scripts\NewVETR\node_modules\grunt\lib\util\task.js:294:30)
  at Task.runTaskFn (C:\ProgramData\scripts\NewVETR\node_modules\grunt\lib\util\task.js:244:24)
  at Task.<anonymous> (C:\ProgramData\scripts\NewVETR\node_modules\grunt\lib\util\task.js:293:12)
  at C:\ProgramData\scripts\NewVETR\node_modules\grunt\lib\util\task.js:220:11
  at _combinedTickCallback (internal/process/next_tick.js:67:7)
  at process._tickCallback (internal/process/next_tick.js:98:9)
  at Module.runMain (module.js:592:11)
  at run (bootstrap_node.js:394:7)
  at startup (bootstrap_node.js:149:9)
  at bootstrap_node.js:509:3


Aborted due to warnings.
```

**Comment by SomaticIT** [comment]
Hello,
Can you show your template files (header/footer)?
The error seems to come from the inner templates.
Thanks

**Comment by Per4merKC** [comment]
Sure!  It's very generic, as I was trying to isolate the issue:

```html
<section class="sectionHeader">
     <div>
          Logo Goes Here
     </div>
     <div>
          Logout
     </div>
</section>
```

**Comment by SomaticIT** [comment]
I do not see any reference of `pkg` inside your templates.
Is it the complete `index.htm` file?
Thanks

**Comment by Per4merKC** [comment]
Yes, this was the entire index.htm.  I presumed that the pkg was a reference inside the grunt-html-build package.

**Comment by SomaticIT** [comment]
Hello,

Verry sorry for the delay.

I looked at the `load-grunt-config` documentation and data which should be added to the `grunt.initConfig` call should be placed into a `data` property.

You `Gruntfile.js` should look like this:
```javascript
module.exports = function (grunt) {
	require('time-grunt')(grunt);
	require('load-grunt-config')(grunt, {
		init: true,
                data: {
			pkg: grunt.file.readJSON("./package.json"),
		},
		loadGruntTasks: {
			pattern: 'grunt-*',
			config: require('./package.json'),
			scope: 'devDependencies'
		},
		jitGrunt: {
			staticMappings: {
				htmlbuild: 'grunt-html-build'
			}
		}
	});
}
```

Thanks
