### ISSUE TITLE
Option-Syntax does not match with the documentation

### ISSUE THREAD

**Issue by tkoelpin** [spatools/grunt-html-build#95]
Hello,

I added the following setting in the gruntfile:

````js
htmlbuild: {
    build: {
        src: ['<%= path.src %>/**/*.*', '!<%= path.src %>/modules/**/*.*'],
        dest: '<%= path.build %>/',
        options: {
            basePath: '<%= path.src %>/',
            logOptions: true,
            relative: true,
            sections: {
                head: '<%= path.templates %>/head.tmpl',
                header: '<%= path.templates %>/header.tmpl',
                footer: '<%= path.templates %>/footer.tmpl'
            }
        }
    }
}
````

But when I log the grunt console with the command `grunt htmlbuild:build -d -v --stack`

I get the following output:

````bash
Running tasks: htmlbuild:build

Running "htmlbuild:build" (htmlbuild) task
[D] Task source: E:\tobias.koelpin\webserver\www\3pam\management\node_modules\grunt-html-build\tasks\build-html.js
Verifying property htmlbuild.build exists in config...OK
Files: src/company/index.php, src/department/index.php, src/index.php, src/netpart/index.php, src/overview.php, src/portal/index.php, src/supporter/index.php, src/user/index.php -> build/
Options: beautify=false, logOptionals=false, relative, basePath="src/", keepTags=false, scripts={}, styles={}, sections={"head":"src/modules/templates/head.tmpl","header":"src/modules/templates/header.tmpl","footer":"src/modules/templates/footer.tmpl"}, data={}, parseTag="build", processFiles=false, processPath=undefined, logOptions
Reading src/company/index.php...OK
Warning: An error occurred while processing a template (Invalid or unexpected token). Use --force to continue.
````

May I draw your attention to the error: __logOptionals=false,__

In the documentation is the following setting: __logOptions: true,__

Now my Question is: What's wrong here?
Oh, by the way, I attached for the developer the current error log, but I commented out the path as [...] for privacy reasons:

````
SyntaxError: An error occurred while processing a template (Invalid or unexpected token).
    at Function (<anonymous>:null:null)
    at [...]\node_modules\lodash\lodash.js:14866:16
    at apply ([...]\node_modules\lodash\lodash.js:473:27)
    at [...]\node_modules\lodash\lodash.js:15250:16
    at apply ([...]\node_modules\lodash\lodash.js:475:27)
    at [...]\node_modules\lodash\lodash.js:6569:16
    at Function.template ([...]\node_modules\lodash\lodash.js:14865:20)
    at Object.template.process ([...]\node_modules\grunt\lib\grunt\template.js:66:27)
    at [...]\node_modules\grunt\lib\grunt\config.js:66:27
    at recurse ([...]\node_modules\grunt-legacy-util\index.js:128:14)
    at recurse ([...]\node_modules\grunt-legacy-util\index.js:120:20)
    at [...]\node_modules\grunt-legacy-util\index.js:111:16
    at Array.map (<anonymous>:null:null)
    at recurse ([...]\node_modules\grunt-legacy-util\index.js:110:20)
    at recurse ([...]\node_modules\grunt-legacy-util\index.js:120:20)
    at recurse ([...]\node_modules\grunt-legacy-util\index.js:120:20)
    at recurse ([...]\node_modules\grunt-legacy-util\index.js:120:20)
    at recurse ([...]\node_modules\grunt-legacy-util\index.js:120:20)
    at Object.util.recurse ([...]\node_modules\grunt-legacy-util\index.js:131:10)
    at Function.config.process ([...]\node_modules\grunt\lib\grunt\config.js:52:21)
    at Function.config.get ([...]\node_modules\grunt\lib\grunt\config.js:46:17)
    at Object.module.exports [as config] ([...]\node_modules\grunt\lib\grunt\config.js:12:19)
    at transformContent ([...]\node_modules\grunt-html-build\tasks\build-html.js:333:28)
    at [...]\node_modules\grunt-html-build\tasks\build-html.js:432:27
    at Array.forEach (<anonymous>:null:null)
    at [...]\node_modules\grunt-html-build\tasks\build-html.js:407:22
    at Array.forEach (<anonymous>:null:null)
    at Object.<anonymous> ([...]\node_modules\grunt-html-build\tasks\build-html.js:403:20)
    at Object.<anonymous> ([...]\node_modules\grunt\lib\grunt\task.js:252:15)
    at Object.thisTask.fn ([...]\node_modules\grunt\lib\grunt\task.js:70:16)
    at Object.<anonymous> ([...]\node_modules\grunt\lib\util\task.js:294:30)
    at Task.runTaskFn ([...]\node_modules\grunt\lib\util\task.js:244:24)
    at Task.<anonymous> ([...]\node_modules\grunt\lib\util\task.js:293:12)
    at Task.start ([...]\node_modules\grunt\lib\util\task.js:302:5)
    at Object.grunt.tasks ([...]\node_modules\grunt\lib\grunt.js:155:8)
    at Liftoff.<anonymous> ([...]\AppData\Roaming\npm\node_modules\grunt-cli\bin\grunt:66:13)
    at Liftoff.execute ([...]\AppData\Roaming\npm\node_modules\grunt-cli\node_modules\liftoff\index.js:203:12)
    at module.exports ([...]\AppData\Roaming\npm\node_modules\grunt-cli\node_modules\flagged-respawn\index.js:51:3)
    at Liftoff.<anonymous> ([...]\AppData\Roaming\npm\node_modules\grunt-cli\node_modules\liftoff\index.js:195:5)
    at Liftoff.<anonymous> ([...]\AppData\Roaming\npm\node_modules\grunt-cli\node_modules\liftoff\index.js:170:7)
    at process._tickCallback (internal/process/next_tick.js:61:11)
````

**Comment by SomaticIT** [comment]
Hello,

Sorry for the delay...
We fixed the syntax issue in documentation.

Your issue is a syntax issue inside the template.
You should have a template tag which is miswritten or not closed...

Thanks
